unit U_problem12 ;

{ The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first
ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first 7 triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28

We can see that the 7th triangle number, 28, is the first triangle number to
have over five factors.

Which is the first triangle number to have over five-hundred factors?
}


interface

uses
  Windows, Messages, SysUtils, Classes, Graphics, Controls, Forms, Dialogs,
  StdCtrls;

type
  TForm1 = class(TForm)
    Memo1: TMemo;
    Button1: TButton;
    procedure Button1Click(Sender: TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  Form1: TForm1;

implementation

{$R *.DFM}

function nbrfactors(n:integer):integer;
var
  i:integer;
begin
  result:=0;
  for i:= 1 to trunc(0.0+sqrt(n))-1 do
  if n mod i = 0 then result:=result+2;
  if n mod trunc(0.0+sqrt(n)) =0 then inc(result); {perfect square}


end;

procedure TForm1.Button1Click(Sender: TObject);
var
  i,t,n:integer;
begin
  t:=1;
  for i:= 2 to 100000 do
  begin
    t:=t+i;
    n:= nbrfactors(t);
    if n>500 then
    begin
      showmessage(inttostr(t)+ ' has '+inttostr(n)+ ' factors');
      break;
    end;
  end;
end;

end.
