unit U_Problem2;

{
Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Find the sum of all the even valued terms in the sequence below one million.
}


interface

uses
  Windows, Messages, SysUtils, Classes, Graphics, Controls, Forms, Dialogs,
  StdCtrls;

type
  TForm1 = class(TForm)
    Memo1: TMemo;
    Button1: TButton;
    ListBox1: TListBox;
    ListBox2: TListBox;
    procedure Button1Click(Sender: TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  Form1: TForm1;

implementation

{$R *.DFM}

procedure TForm1.Button1Click(Sender: TObject);
var i:integer;
    prevterm, currterm, temp, sum :integer;
begin
  prevterm:=0;
  currterm:=1;
  sum:=0;
  for i:=1 to  50 do
  begin
    temp:=prevterm+currterm;
    prevterm:=currterm;
    currterm:=temp;
    if (currterm mod 2 = 0) and (currterm>=1000000) then break;
    listbox1.Items.add(inttostr(currterm));
    if currterm mod 2 =0  then
    begin
      sum:=sum+currterm;
      listbox2.items.add(inttostr(currterm)+' Sum: '+inttostr(sum));
    end;
  end;
  showmessage('Sum of even fibo terms up to 1,000,000 is '+inttostr(sum));
end;

end.
